name: OpenWrt Package Build


on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: openwrtorg/sdk:${{ matrix.target }}
    strategy:
      matrix:
        target:
          - ath79-nand
    steps:
      - name: Prepare feeds
        run: |
          echo "src-link kconfiglib https://github.com/plume-design/opensync-openwrt/feeds/lang" >> feeds.conf
          echo "src-link opensync https://github.com/plume-design/opensync-openwrt/feeds/network" >> feeds.conf
          #./scripts/feeds update -a
          #./scripts/feeds install -a
          #package/opensync/compile OPENSYNC_SRC=https://github.com/plume-design/opensync-openwrt TARGET=ath79-nand
        working-directory: /home/build/openwrt
      - name: Install packages
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
        working-directory: /home/build/openwrt
      - name: Compile
        run: |
          ls package
          package/opensync/compile OPENSYNC_SRC=https://github.com/plume-design/opensync-openwrt TARGET=ath79-nand
        working-directory: /home/build/openwrt
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: binaries
          path: bin/packages/
