name: OpenWrt Package Build


on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: openwrtorg/sdk:${{ matrix.target }}
    strategy:
      matrix:
        target:
          - ath79-nand
    steps:
      - name: Prepare feeds
        run: |
          echo 'src-git base https://github.com/openwrt/openwrt.git' > feeds.conf
          echo 'src-git custom https://github.com/sdyear/openwrt-packages.git' >> feeds.conf
          ./scripts/feeds update -a
        working-directory: /home/build/openwrt
      - name: Install packages
        run: |
          ./scripts/feeds install -p custom ${{ matrix.package }}
        working-directory: /home/build/openwrt
      - name: Configure
        run: |
          make defconfig
        working-directory: /home/build/openwrt
      - name: Compile
        run: |
          make package/${{ matrix.package }}/compile
        working-directory: /home/build/openwrt
      - name: Fetch signing key
        run: |
          echo "${{ secrets.REPO_SECRET_KEY }}" > key-build
        working-directory: /home/build/openwrt
      - name: Create package index
        run: |
          make package/index
        working-directory: /home/build/openwrt
      - name: Store binaries
        run: |
          sudo rsync -a /home/build/openwrt/bin/ ./bin/
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: binaries
          path: bin/packages/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git
        uses: actions/checkout@v2
      - name: Collect artifacts
        uses: actions/download-artifact@v1
        with:
          name: binaries
          path: bin/
      - name: Build repo layout
        run: |
          mkdir repo/
          for arch in bin/*; do
            mv $arch/custom/ repo/$(basename ${arch})/
            cp repo-key.pub repo/$(basename ${arch})/
          done
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: repo
          path: repo/
