name: OpenWrt Package Build


on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: openwrtorg/sdk:${{ matrix.target }}
    strategy:
      matrix:
        target:
          - ath79-nand
    steps:
      - name: Download repo
        run: |
          git clone https://github.com/sdyear/opensync-openwrt.git
        working-directory: /home/build/openwrt
      - name: Install packages
        run: |
          ../scripts/feeds update -a
          ../scripts/feeds install -a
        working-directory: /home/build/openwrt/opensync-openwrt/
      - name: Install Docker
        run: |
          sudo apt-get update
          #sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common -y
          #curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          #sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs) stable"
          #sudo apt-get update
          sudo apt-get install docker.io -y #-ce docker-ce-cli containerd.io -y
          sudo groupadd docker
          sudo usermod -aG docker $USER
          #su -s ${USER}
          newgrp docker
      - name: Compile
        run: |
          #make package/opensync/compile OPENSYNC_SRC=/home/build/openwrt/opensync-openwrt TARGET=ath79-nand
          make TARGET=ATH79 SDK_URL=https://mirror.fsmg.org.nz/openwrt/releases/19.07.1/targets/ath79/nand/openwrt-sdk-19.07.1-ath79-nand_gcc-7.5.0_musl.Linux-x86_64.tar.xz
        working-directory: /home/build/openwrt/opensync-openwrt/example/
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: binaries
          path: bin/packages/
