name: OpenWrt Package Build


on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: openwrtorg/sdk:${{ matrix.target }}
    strategy:
      matrix:
        target:
          - ath79-nand
    steps:
      - name: Download repo
        run: |
          git clone https://github.com/sdyear/opensync-openwrt.git
        working-directory: /home/build/openwrt
      - name: Install packages
        run: |
          ../scripts/feeds update -a
          ../scripts/feeds install -a
        working-directory: /home/build/openwrt/opensync-openwrt/
      - name: Compile
        run: |
          #make package/opensync/compile OPENSYNC_SRC=/home/build/openwrt/opensync-openwrt TARGET=ath79-nand
          make TARGET=ATH79 SDK_URL=https://mirror.fsmg.org.nz/openwrt/releases/19.07.1/targets/ath79/nand/openwrt-sdk-19.07.1-ath79-nand_gcc-7.5.0_musl.Linux-x86_64.tar.xz
        working-directory: /home/build/openwrt/opensync-openwrt/example/
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: binaries
          path: bin/packages/
