name: OpenWrt Package Build


on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: openwrtorg/sdk:${{ matrix.target }}
    strategy:
      matrix:
        target:
          - ath79-nand
    steps:
      - name: Download repo
        run: |
          git clone https://github.com/plume-design/opensync-openwrt.git
          working-directory: /home/build/openwrt
      - name: Download repo
        run: |
          git clone https://github.com/plume-design/opensync.git
          rm -r core
          mv opensync/ core/
        working-directory: /home/build/openwrt/opensync-openwrt/opensync/
      - name: Prepare feeds
        run: |
          echo "src-link kconfiglib /home/build/openwrt/opensync-openwrt/feeds/lang" >> feeds.conf
          echo "src-link opensync /home/build/openwrt/opensync-openwrt/feeds/network" >> feeds.conf
          echo "src-git base https://git.openwrt.org/openwrt/openwrt.git" >> feeds.conf
          echo "src-git packages https://git.openwrt.org/feed/packages.git" >> feeds.conf    
        working-directory: /home/build/openwrt
      - name: Install packages
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
        working-directory: /home/build/openwrt
      - name: Compile
        run: |
          make package/opensync/compile OPENSYNC_SRC=/home/build/openwrt/opensync-openwrt TARGET=ath79-nand
        working-directory: /home/build/openwrt
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: binaries
          path: bin/packages/
